#!/bin/bash
# Does not use asoundconf because unfortunately it has been deprecated
# See: http://linuxcommand.org/lc3_adv_dialog.php

# Define the dialog exit status codes
: ${DIALOG_OK=0}
: ${DIALOG_EXTRA=123}

: ${CONFILE=~/.asoundrc}

# Duplicate file descriptor 1 (stdout) on descriptor 3 (stderr)
exec 3>&1

result=$(cat /proc/asound/cards | sed -n 's/^ *\([0-9]\+\)[^:]*: \(.*\)$/\1\n\2/p' |
  xargs -d'\n' dialog --extra-button --extra-label 'Set&Mixer' --menu 'Select default soundcard' 12 40 5 2>&1 1>&3)

# Get dialog's exit status
return_value=$?

# Close file descriptor 3
exec 3>&-

set-default-card () {
    echo "defaults.ctl.card $result;
defaults.pcm.card $result;" >"$CONFILE"
}

# Act on the exit status
case $return_value in
  $DIALOG_OK)
    set-default-card "$result";;
  $DIALOG_EXTRA)
    # I don't know why DIALOG_CANCEL (1) is not returned on cancel
    if [ "$result" ]; then
      set-default-card "$result"
      alsamixer
    fi;;
esac

clear
